export const ADD_NEWS = 'ADD_NEWS'
export const ADD_IDS = 'ADD_IDS'
export const CHANGE_CURRENT_NEWS_ID = 'CHANGE_CURRENT_NEWS_ID'
export const ADD_ALL_NEWS = 'ADD_ALL_NEWS'
export const ADD_DATE = 'ADD_DATE'
export const ADD_DATE_STR = 'ADD_DATE_STR'
export const ADD_MORE_IDS = 'ADD_MORE_IDS'
export const ADD_HOMEPAGE_DATE = 'ADD_HOMEPAGE_DATE'
export const ADD_HOMEPAGE_DATE_STR = 'ADD_HOMEPAGE_DATE_STR'

export const SET_POPULARITY = 'SET_POPULARITY'

export const SET_COLLECT_STATE = 'SET_COLLECT_STATE'

export const SET_COLLECT_NEWS = 'SET_COLLECT_NEWS'
